### ISSUE TITLE
As a player, I want to hear sounds when I start/win the game

### ISSUE THREAD

**Issue by PhamMinhTung** [PhamMinhTung/FixPongGame#23]

**Comment by PhamMinhTung** [comment]
Tìm hiểu code: 10 minutes
tìm âm thanh: 5 minutes
Ghi code: 15 minutes

Đánh code: 30 minutes
Tìm các lỗi sai nếu có:30 minutes
Kiểm tra 15 minutes

**Comment by drive3** [comment]
Done

**Comment by PhamMinhTung** [comment]
The code is in #26
