### ISSUE TITLE
As a player, I want to be able to set my name and show it on screen

### ISSUE THREAD

**Issue by PhamMinhTung** [PhamMinhTung/FixPongGame#27]

**Comment by PhamMinhTung** [comment]
1.Time for thinking: 30 minutes 
Tìm hiểu code: 15 minutes 
 code: 15 minutes
 2.Time for working: 1 hours
 Đánh code: 30 minutes 
Tìm lỗi sai khi đánh code: 15 minutes 
3.Time for testing: 10 minutes

**Comment by drive3** [comment]
Done
